config/routes.rb
Rails.application.routes.draw do
  resources :questions
  resources :advertisements


  resources :topics do
    # resources:posts pass the resources :topics. this rests the post routes under the topic routes
     resources :posts, except: [:index]
     resources :sponsored_posts
   end

# only: [] is used so we donot create any posts/:id routes
   resources :posts, only: [] do
     resources :favorites, only: [:create, :destroy]
     # we only add create and destroy routes
     resources :comments, only: [:create, :destroy]
     post '/up-vote' => 'votes#up_vote', as: :up_vote
     post '/down-vote' => 'votes#down_vote', as: :down_vote
   end
   #only hash key will prevent rails from creating other routes than new and create
  resources :users, only: [:new, :create, :show]
    post 'users/confirmation' => 'users#confirmation'

  resources :sessions, only: [:new, :create, :destroy]

  get 'about' => 'welcome#about'

  get 'contact' => 'welcome#contact'

  get 'faq' => 'welcome#faq'

  root 'welcome#index'
end

app/models/question.rb
class Question < ApplicationRecord
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def index
    @questions = Question.all
  end

  def show
    @question = Question.find(params[:id])
  end

  def new
    @question = Question.new
  end

  def create
    @question = Question.new
    @question.title = params[:question][:title]
    @question.body = params[:question][:body]
    @question.resolved = params[:question][:resolved]

    if @question.save
      flash[:notice] = "Question was posted."
      redirect_to @question
    else
      flash.now[:alert] = "Error occured, try again."
      render :new
    end
  end

  def edit
    @question = Question.find(params[:id])
  end

  def update
    @question = Question.find(params[:id])
    @question.title = params[:question][:title]
    @question.body = params[:question][:body]
    @question.resolved = params[:question][:resolved]

    if @question.save
      flash[:notice] = "Question was updated."
      redirect_to @question
    else
      flash.now[:alert] = "An error occured, please try again."
      render :edit
    end

  end

  def destroy
    @question = Question.find(params[:id])

    if @question.destroy
      flash[:notice] = "\"#{@question.title}\" was deleted successfully."
      redirect_to questions_path
    else
      flash.now[:alert] = "Error occured while deleting the question."
      render :show
    end
  end

end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/edit.html.erb
<div class="new-row">
  <div class="guidelines">
    <h2> Guidelines for posting on Jimmidit </h2>
    <ul>
      <li> Freedom of speech does not mean freedom of consequences.</li>
      <li> BNBR. Be nice be respectful to your fellow posters </li>
    </ul>
  </div>

  <div class="new-post">
    <%= form_for @question do |q| %>
      <div class="form-group">
        <%= q.label :title %>
        <%= q.text_field :title, class: 'form-control', placeholder: "Enter question title" %>
      </div>

      <div class="form-group">
        <%= q.label :body %>
        <%= q.text_area :body, rows: 3, class: 'form-control', placeholder: "Enter question body" %>
      </div>

      <div class="form-group">
         Resolved? <%= q.check_box :resolved %>
      </div>

      <div class="form-group">
        <%= q.submit "Save", class: 'btn btn-success' %>
      </div>
    <% end %>
  </div>

</div>

app/views/questions/index.html.erb
<h1>All Questions</h1>

<% @questions.each do |question| %>
  <div class = "media">
    <div class = "media-body">
      <h4 class = "media-heading">
        <%= link_to question.title, question %>
      </h4>
    </div>
  </div>
<% end %>

app/views/questions/new.html.erb
<div class="new-row">
  <div class="guidelines">
    <h2> Guidelines for posting on Jimmidit</h2>
    <ul>
      <li> Freedom of speech does not mean freedom of consequences.</li>
      <li> BNBR. Be nice be respectful to your fellow posters </li>
    </ul>
  </div>

  <div class="new-post">
    <%= form_for @question do |q| %>
      <div class="form-group">
        <%= q.label :title %>
        <%= q.text_field :title, class: 'form-control', placeholder: "Enter question title" %>
      </div>

      <div class="form-group">
        <%= q.label :body %>
        <%= q.text_area :body, rows: 3, class: 'form-control', placeholder: "Enter question body" %>
      </div>

      <div class="form-group">
        <%= q.submit "Save", class: 'btn btn-success' %>
      </div>
    <% end %>
  </div>

</div>

app/views/questions/show.html.erb
<h1><%= @question.title %></h1>

<div class="resolved-button">
    <%= @question.resolved %>
</div>

<div class="new-question">
  <div class="form-group">
    <p><%= @question.body %></p>
  </div>
  <div class="edit-question">
    <%= link_to "Edit", edit_question_path(@question), class: 'btn btn-success' %>
    <%= link_to "Delete", @question, method: :delete, class: 'btn btn-danger', data: {confirm: "You are about to delete this question, proceed?"} %>
  </div>
</div>