config/routes.rb
Rails.application.routes.draw do
  resources :questions
  resources :advertisements


  resources :topics do
    # resources:posts pass the resources :topics. this rests the post routes under the topic routes
     resources :posts, except: [:index]
     resources :sponsored_posts
   end

# only: [] is used so we donot create any posts/:id routes
   resources :posts, only: [] do
     resources :favorites, only: [:create, :destroy]
     # we only add create and destroy routes
     resources :comments, only: [:create, :destroy]
     post '/up-vote' => 'votes#up_vote', as: :up_vote
     post '/down-vote' => 'votes#down_vote', as: :down_vote
   end
   #only hash key will prevent rails from creating other routes than new and create
  resources :users, only: [:new, :create, :show]
    post 'users/confirmation' => 'users#confirmation'

  resources :sessions, only: [:new, :create, :destroy]

  get 'about' => 'welcome#about'

  get 'contact' => 'welcome#contact'

  get 'faq' => 'welcome#faq'

  root 'welcome#index'
end

app/models/topic.rb
class Topic < ApplicationRecord
  has_many :posts, dependent: :destroy
  has_many :sponsored_posts, dependent: :destroy

  validates :name, length: { minimum: 5}, presence: true
  validates :description, length: { minimum: 15}, presence: true 
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController

before_action :require_sign_in, except: [:index, :show]
before_action :authorize_user, except: [:index, :show, :edit, :update]
before_action :moderator, except: [:index, :show, :new, :create, :destroy]

  def index
    @topics = Topic.all
  end

  def show
    @topic = Topic.find(params[:id])
  end

  def new
    @topic = Topic.new
  end

  def create
  @topic = Topic.new(topic_params)

   if @topic.save
     redirect_to @topic, notice: "Topic was saved successfully."
   else
     flash.now[:alert] = "Error creating topic. Please try again."
     render :new
   end
  end

  def edit
    @topic = Topic.find(params[:id])
  end

  def update
    @topic = Topic.find(params[:id])
    @topic.assign_attributes(topic_params)

    if @topic.save
       flash[:notice] = "Topic was updated."
      redirect_to @topic
    else
      flash.now[:alert] = "Error saving topic. Please try again."
      render :edit
    end
  end

  def destroy
    @topic = Topic.find(params[:id])

    if @topic.destroy
      flash[:notice] = "\"#{@topic.name}\" was deleted successfully."
      redirect_to action: :index
    else
      flash.now[:alert] = "There was an error deleting the topic."
      render :show
    end
  end

  private
  def topic_params
    params.require(:topic).permit(:name, :description, :public)
  end

  def authorize_user
    unless current_user.admin?
      flash[:alert] = "You must be authorized to do that."
      redirect_to topics_path
    end
  end

  def moderator
    unless current_user.moderator? || current_user.admin?
      flash[:alert] = "You must be authorized to do that."
      redirect_to topics_path
    end
  end
end

app/helpers/topics_helper.rb
module TopicsHelper
  def user_is_authorized_to_edit?
    current_user.admin? || current_user.moderator?
  end

  def user_is_admin?
    current_user.admin?
  end
end

app/views/topics/_form.html.erb
<%= form_for topic do |t| %>

  <% if topic.errors.any? %>
    <div class="alert alert-danger">
      <h4> <%= pluralize(topic.errors.count, "error") %>.</h4>
      <ul>
        <% topic.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= form_group_tag(topic.errors[:name]) do %>
    <%= t.label :name %>
    <%= t.text_field :name, class: 'form-control', placeholder: "Enter topic name" %>
  <% end %>

  <%= form_group_tag(topic.errors[:description]) do %>
    <%= t.label :description %>
    <%= t.text_area :description, rows: 7, class: 'form-control', placeholder: "Enter topic description" %>
  <% end %>

  <div class="form-group">
    <%= t.label :public, class: 'checkbox' do %>
      <%= t.check_box :public %> Public topic
    <% end %>
  </div>

  <%= t.submit "Save", class: 'btn btn-success' %>
<% end %>

app/views/topics/_topic.html.erb
<div class="media">
  <div class="media-body">
    <h4 class="media-heading">
      <%= link_to topic.name, topic %>
    </h4>
    <small>
      <%= topic.description %>
    </small>
  </div>
</div>

app/views/topics/edit.html.erb
<h1>Edit Topic</h1>

<div class="new-row">
  <div class="guidelines">
    <h2> Guidelines for posting on Jimmidit</h2>
    <ul>
      <li> Freedom of speech does not mean freedom of consequences.</li>
      <li> BNBR. Be nice be respectful to your fellow posters </li>
    </ul>
  </div>

  <div class="new-post">
    <%= render partial: 'form', locals: {topic: @topic} %>
  </div>
</div>

app/views/topics/index.html.erb
<h1>Topics</h1>

<div class="row">
  <div class="col-md-8">

    <% @topics.each do |topic| %>
      <%= render partial: 'topics/topic', locals: {topic: topic} %>
      <%= topic.posts.count %> posts
    <% end %>
  </div>
  <% if current_user && user_is_admin? %>
    <div class="col-md-4">
      <%= link_to "New Topic", new_topic_path, class: 'btn btn-success' %>
    </div>
  <% end %>
</div>

app/views/topics/new.html.erb
<h1>New Topic</h1>

<div class="new-row">
  <div class="guidelines">
    <h2> Guidelines for posting on Jimmidit </h2>
    <ul>
      <li> Freedom of speech does not mean freedom of consequences.</li>
      <li> BNBR. Be nice be respectful to your fellow posters </li>
    </ul>
  </div>

  <div class="new-post">
    <%= render partial: 'form', locals: {topic: @topic} %>
  </div>
</div>

app/views/topics/show.html.erb
<h1><%= @topic.name %></h1>

<% if current_user && user_is_authorized_to_edit? %>
  <%= link_to "Edit Topic", edit_topic_path, class: 'btn btn-success' %>
<% end %>
<% if current_user && user_is_admin? %>
  <%= link_to "Delete Topic", @topic, method: :delete, class: 'btn btn-danger', data: { confirm: 'You are about to delete this topic, please confirm' } %>
<% end %>

<div class="row">
  <div class="col-md-8">
    <p class="lead"><%= @topic.description %></p>
<!-- #10 -->
    <% @topic.posts.each do |post| %>
      <div class="media">
        <%= render partial: 'votes/voting', locals: { post: post } %>
        <div class="media-body">
          <h4 class="media-heading">
            <%= link_to post.title, topic_post_path(@topic, post) %>
          </h4>
          <small>
            submitted <%= time_ago_in_words(post.created_at) %> ago by <%= post.user.name %> <br>
            <%= post.comments.count %> Comments
          </small>
        </div>
      </div>
    <% end %>

    <h3> Sponsored Posts </h3>
    <% @topic.sponsored_posts.each do |sponsored_post| %>
      <div class="media">
        <div class="media-body">
          <h4 class="media-heading">
            <%= link_to sponsored_post.title, topic_sponsored_post_path(@topic, sponsored_post) %>
          </h4>
          <small>
            submitted <%= time_ago_in_words(sponsored_post.created_at) %> ago <br>
          </small>
        </div>
      </div>
    <% end %>
  </div>
  <div class="col-md-4">
    <% if current_user %>
      <%= link_to "New Post", new_topic_post_path(@topic), class: 'btn btn-success' %>
    <% end %>
    <% if current_user && user_is_admin? %>
      <%= link_to "New Sponsored Post", new_topic_sponsored_post_path(@topic), class: 'btn btn-success' %>
    <% end %>
  </div>
</div>