config/routes.rb
Rails.application.routes.draw do
  resources :questions
  resources :advertisements


  resources :topics do
    # resources:posts pass the resources :topics. this rests the post routes under the topic routes
     resources :posts, except: [:index]
     resources :sponsored_posts
   end

# only: [] is used so we donot create any posts/:id routes
   resources :posts, only: [] do
     resources :favorites, only: [:create, :destroy]
     # we only add create and destroy routes
     resources :comments, only: [:create, :destroy]
     post '/up-vote' => 'votes#up_vote', as: :up_vote
     post '/down-vote' => 'votes#down_vote', as: :down_vote
   end
   #only hash key will prevent rails from creating other routes than new and create
  resources :users, only: [:new, :create, :show]
    post 'users/confirmation' => 'users#confirmation'

  resources :sessions, only: [:new, :create, :destroy]

  get 'about' => 'welcome#about'

  get 'contact' => 'welcome#contact'

  get 'faq' => 'welcome#faq'

  root 'welcome#index'
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :topic
  belongs_to :user

  has_many :comments, dependent: :destroy
  has_many :votes, dependent: :destroy
  has_many :favorites, dependent: :destroy

  after_create :create_vote
  after_create :create_favorite

#this allow posts to be organized by date
  default_scope { order('rank DESC') }

  scope :visible_to, -> (user) { user ? all : joins(:topic).where('topics.public' => true) }
  # makes comments dependent on posts existence
  # when posts are deleted the comments are deleted as well

  validates :title, length: { minimum: 5}, presence: true
  validates :body, length: { minimum: 20}, presence: true
  validates :topic, presence: true
  validates :user, presence: true

  def up_votes
    votes.where(value: 1).count
  end

  def down_votes
    votes.where(value: -1).count
  end

  def points
    votes.sum(:value)
  end

  def update_rank
    age_in_days = (created_at - Time.new(1970,1,1)) / 1.day.seconds
    new_rank = points + age_in_days
    update_attribute(:rank, new_rank)
  end

  private
  def create_vote
    user.votes.create(value: 1, post: self)
  end

  def create_favorite
    Favorite.create(post: self, user: self.user)
    FavoriteMailer.new_post(self).deliver_now
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  #this call the require_sign_in action, except for show.
  before_action :require_sign_in, except: :show
  before_action :moderator, except: [:show, :new, :create, :destroy]
  before_action :authorize_user, except: [:show, :new, :create, :edit, :update]

  def index
    @posts.each_with_index do |post,index|
      if (index + 1) % 5 == 0
        post.title = "SPAM"
      end
    end
  end

  def show
    @post = Post.find(params[:id])
  end

  def new
    @topic = Topic.find(params[:topic_id])
    @post = Post.new
  end

  def create
    @post = Post.new
    @post.title = params[:post][:title]
    @post.body = params[:post][:body]
    @topic = Topic.find(params[:topic_id])
    @post.topic = @topic
    @post.user = current_user

    if @post.save
      flash[:notice] = "Post was saved."
      redirect_to [@topic, @post]
    else
      flash.now[:alert] = "There was an error. Try again."
      render :new
    end

  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    @post.assign_attributes(post_params)

    if @post.save
      flash[:notice] = "Post was updated."
      redirect_to [@post.topic, @post]
    else
      flash.now[:alert] = "An error occured, please try again."
      render :edit
    end

  end

  def destroy
    @post = Post.find(params[:id])

    if @post.destroy
      flash[:notice] = "\"#{@post.title}\" was deleted successfully."
      redirect_to @post.topic
    else
      flash.now[:alert] = "Error occured while deleting the post."
      render :show
    end
  end

  private
  def post_params
    params.require(:post).permit(:title, :body)
  end

  def moderator
    post = Post.find(params[:id])

    unless current_user == post.user || current_user.admin? || current_user.moderator?
      flash[:alert] = "You must be authorized to do that."
      redirect_to [post.topic, post]
    end
  end

  def authorize_user
    post = Post.find(params[:id])

    unless current_user == post.user || current_user.admin?
      flash[:alert] = "You must be authorized to do that."
      redirect_to [post.topic, post]
    end
  end

end

app/helpers/posts_helper.rb
module PostsHelper
  def user_can_edit?(post)
    current_user && (current_user == post.user || current_user.admin? || current_user.moderator?)
  end

  def user_can_delete?(post)
    current_user && (current_user == post.user || current_user.admin?)
  end
end

app/views/posts/_form.html.erb
<%= form_for [topic, post] do |p| %>

  <% if post.errors.any? %>
    <div class="alert alert-danger">
      <h4> <%= pluralize(post.errors.count, "error") %>.</h4>
      <ul>
        <% post.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul
    </div>
  <% end %>

  <%= form_group_tag(post.errors[:title]) do %>

    <%= p.label :title %>
    <%= p.text_field :title, class: 'form-control', placeholder: "Enter post title" %>
  <% end %>

  <%= form_group_tag(post.errors[:body]) do %>
    <%= p.label :body %>
    <%= p.text_area :body, rows: 7, class: 'form-control', placeholder: "Enter post body" %>
  <% end %>

  <div class="form-group">
    <%= p.submit "Save", class: 'btn btn-success' %>
  </div>

<% end %>

app/views/posts/_post-user.html.erb
<div>
  <%= render partial: 'votes/voting', locals: { post: @post } %>
  <h2>
    <%= @post.title %> <br>
    <small>
      submitted <%= time_ago_in_words(@post.created_at) %> ago by <%= @post.user.name %>
    </small>
  </h2>
</div>

app/views/posts/_post.html.erb
<div class="media">
  <%= render partial: 'votes/voting', locals: { post: post } %>
  <div class="media-body">
    <h4 class="media-heading">
      <div class="pull-left">
        <%= image_tag post.user.avatar_url(128), class: 'gravatar-thumb' %>
      </div>
        <%= link_to post.title, topic_post_path(post.topic, post) %>
    </h4>
    <small>
      submitted <%= time_ago_in_words(post.created_at) %> ago by <%= post.user.name %> <br>
      <%= post.comments.count %> Comments
    </small>
  </div>
</div>

app/views/posts/edit.html.erb
<div class="new-row">
  <div class="guidelines">
    <h2> Guidelines for posting on Jimmidit </h2>
    <ul>
      <li> Freedom of speech does not mean freedom of consequences.</li>
      <li> BNBR. Be nice be respectful to your fellow posters </li>
    </ul>
  </div>

  <div class="new-post">
     <%= render partial: 'form', locals: { topic: @post.topic, post: @post } %>
  </div>

</div>

app/views/posts/new.html.erb
<div class="new-row">
  <div class="guidelines">
    <h2> Guidelines for posting on Jimmidit </h2>
    <ul>
      <li> Freedom of speech does not mean freedom of consequences.</li>
      <li> BNBR. Be nice be respectful to your fellow posters </li>
    </ul>
  </div>

  <div class="new-post">
    <%= render partial: 'form', locals: { topic: @topic, post: @post } %>
  </div>

</div>

app/views/posts/show.html.erb
 <div class="each-post">

  <%= render partial: 'posts/post-user', locals: { post: @post } %>
  <div class="post-body">
    <p><%= @post.body %></p>
    <div class="comment-section">
      <h3>Comments</h3>
      <%= render @post.comments %>
      <% if current_user %>
        <%= render 'comments/form', comment: Comment.new, post: @post %>
      <% end %>
    </div>
  </div>


  <div class="side-features">
    <div class="post-buttons">
      <% if user_can_edit?(@post) %>
        <div class="edit-post">
          <%= link_to "Edit Post", edit_topic_post_path(@post.topic, @post), class: 'btn btn-success' %>
        <div>
      <% end %>
      <% if user_can_delete?(@post) %>
        <div class="edit-post">
          <%= link_to "Delete Post", [@post.topic, @post], method: :delete, class: 'btn btn-danger', data: {confirm: "You are about to delete this post, proceed?"} %>
        </div>
      <% end %>
    </div>

    <div class="col-md-4">
      <h3>
        <%= pluralize(@post.points, 'point') %>
        <div>
          <small>
            <%= pluralize(@post.up_votes, 'up vote') %>,
            <%= pluralize(@post.down_votes, 'down vote') %>
          </small>
        </div>
      </h3>
      <% if current_user %>
        <%= render partial: 'favorites/favorite', locals: { post: @post } %>
      <% end %>
    </div>
  </div>

</div>